# Generated by Django 5.0.6 on 2024-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タスク名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="詳細"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "未実施"), (1, "実施中"), (2, "完了")],
                        default=0,
                        verbose_name="状況",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(0, "低"), (1, "中"), (2, "高")],
                        default=0,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="期限"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
            ],
        ),
    ]
